/**
 * Noms qu'un slot ne peut pas porter (spec §9.3) : un slot devient un
 * paramètre dans chaque cible, donc jamais un mot réservé de JavaScript, ni un
 * nom que le composant React généré utilise déjà (`s`, `Icon`, `ImageSource`).
 * Le backend CSS les refuse (E004) et le générateur de tests les évite. Un
 * backend futur ajoute ici les siens, pour que le générateur reste valide
 * pour toutes les cibles à la fois.
 */
export const RESERVED_SLOT_NAMES: ReadonlySet<string> = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "arguments",
  "eval",
  "undefined",
  "s",
  "Icon",
  "ImageSource",
]);
